### ISSUE TITLE
[Native Promise] exectute Reject Promise won't go to .catch handler

### ISSUE THREAD

**Issue by lovedota** [charleshansen/mock-promises#19]
Hi @charleshansen 

I have a case

```
var promise1 = Promise.reject('123');

promise1
  .then(() => console.log('Then'))
  .catch(() => console.log('Catch'))

mockPromises.executeForPromise(promise1);

//No console for catch
```

But if I change to this, it works

```
var promise1 = Promise.reject('123');

promise1
  .then(
       () => console.log('Then'),
       () => console.log('Catch')
   );
mockPromises.executeForPromise(promise1);

//It works well
```

**Comment by charleshansen** [comment]
The reason `catch` doesn't work is it adds another layer of `then` to your promise. To get the `catch` to fire, you can add a `mockPromises.iterateForPromise(promise1);` and it should work. 

As a side note, I have personally switched to using `mockPromises.tick()` instead of `executeForPromise` and the like. You still get pretty good control, but it is less annoying to work with. You could just do `mockPromises.tick(2);` instead of the `executeForPromise` followed by `iterateForPromise`.
