### ISSUE TITLE
Support Promise.prototype.all

### ISSUE THREAD

**Issue by joeheyming** [charleshansen/mock-promises#28]
Bluebird has an 'all' function installed on it's constructor and on it's prototype.

they are slightly different:

dothing().then(function() {
   return [ doanother(), doanotherThing() ];
}).all().then(function([thing1, thing2]) {
});

Here is my attempt at supporting it:
  BluebirdPromise.prototype.all = function() {
    var promise = this;
    return new BluebirdPromise(function(resolve, reject) {
      promise.then(function() {
        var promises = Array.prototype.slice.apply(arguments);
        var allPromise = BluebirdPromise.all.apply(this, promises);
        resolve(allPromise);
        return allPromise;
      }, reject);
    });
  };

It works for me, I'm wondering if we can incorporate this.

**Comment by charleshansen** [comment]
Hey, sorry for the late reply...

Thanks for using the library. I'm glad the patch works for you. I've had to [patch](https://github.com/pivotal-cf/react-starter/blob/master/spec/support/bluebird.js) bluebird myself for testing since it is kinda non-standard.

As a general rule, I'd rather not add functionality specific to any one Promise library. Especially Bluebird, since that one has a ton of extra bells and whistles. The worry here is that if someone has code that is using Native Promises, but mock-promises makes them think there is an `all` function on the prototype, their tests will be passing but their implementation will be wrong. 

If you do want this as part of `mock-promises`, I would support adding an extra adapter file, so that someone could write code like this 

```js
const Bluebird = require('bluebird');
const BluebirdAdapter = require('mock-promises/adapters/bluebird')
BluebirdAdapter(Bluebird)
global.Promise = Bluebird
```

The adapter can then add things to the prototype that are specific to the library (like `all` for you and fixing `catch` for me).

As a random aside, I'm honestly not sure why anyone needs the `all` prototype function, in your example, wouldn't it work without the `all`? Maybe I'm missing something.

```js
dothing().then(function() {
return [ doanother(), doanotherThing() ];
}).then(function([thing1, thing2]) {
});
```

**Comment by charleshansen** [comment]
closed for inactivity
