### ISSUE TITLE
when I catch reject, mockPromise.tick() doesn't work

### ISSUE THREAD

**Issue by kinogam** [charleshansen/mock-promises#31]
I use jest to test code 
```javascript
        it('a test', done => {
			function someTest() {
				return new Promise((resolve, reject) => {
					reject('123');
				}).catch(error => console.log(error));
			}

			someTest().then(()=> {}, rejectResult => {
                expect(rejectResult).toBe('123');
				done();
            });

			mockPromises.tick();
        });
```
Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

**Comment by charleshansen** [comment]
Hi there,

Glad you are using the project, here are some pointers that might be useful for you...

`catch` and `reject` work in general. It is technically possible that `catch` doesn't work if you are using an odd promise polyfill that implements `catch` without using `then` internally, let me know your polyfill of the other fixes don't work.

`mockPromises.tick()` will only tick through one generation of `then` or `catch` for each promise chain. In your example, `someTest` returns a promise with a `catch` on it, and then you attach a `then` before expecting the result. This looks like a three deep promise. I think you will find different results if you try `mockPromises.tick(3)` or `mockPromises.tickAllTheWay()` (promise chains can be subtle, maybe the number isn't actually 3 in your real code).

mock promises is designed to turn asynchronous promises into controlled synchronous promises for easier testing. If you are using the `done` callback in jest, the whole think is fundamentally asynchronous. I'm not 100% sure what happens if you use mock promises and `done` in jest at the same time. It might work, but I haven't tried it. You should be able to do something more synchronous like

```js
 it('a test', ()=> {
			function someTest() {
				return new Promise((resolve, reject) => {
					reject('123');
				}).catch(error => console.log(error));
			}

                let rejectResult;
	        someTest().then(()=> {}, x => {rejectResult = x}))
		mockPromises.tick(3);
                expect(rejectResult).toBe('123');
        });
```
Hope that helps,

**Comment by kinogam** [comment]
@charleshansen thx for support, but your code still doesn't work. 

when I remove 
```javascript
     .catch(error => console.log(error));
```
everything works well

I use babel-jest to transform code
```javascript
const babelJest = require('babel-jest');

module.exports = babelJest.createTransformer({
    presets: ['env'],
    plugins: [
        [
            'transform-runtime',
            {
                polyfill: false,
                regenerator: true
            }
        ]
    ]
});

```

**Comment by charleshansen** [comment]
Sorry, I'm on break and can't really play with this code, but a couple more notes

Minor point: your promise won't actually reject to '123' because the catch prevents it, you would need to re-raise the error
```js
.catch(error => {console.log(error); throw error});
```

I'm also not intimately familiar with `babel-jest`, so I can't say for sure what it is doing to your promises. It looks like it might not be doing anything. In this case you should be following the instructions for Native Promises and should have a line like 
```js
Promise = mockPromises.getMockPromise(Promise);
```

I haven't robustly tested all corner cases of the Native Promise solution, but this seems basic enough that it should work. Just to check, does it work if you replace the `catch` with
```js
.then(() => {}, error => {console.log(error); return error});
```
Also, maybe try `mockPromises.tickAllTheWay()` just to be sure.

Native Promises have changed a little bit since I implemented this, if you see something wrong in the code, I'd be happy to look at a PR.

**Comment by kinogam** [comment]
tickAllTheWay work, thx @charleshansen
